### ISSUE TITLE
promote xtype section in doc

### ISSUE THREAD

**Issue by pdowler** [ivoa-std/DALI#27]
Curently, the xtype section "Data Types and Literal Values" is currently hiding under "Parameters" but it really is more general than parameter input as it also covers values in VOTable columns and string values for some ADQL constructor functions (not explicit in all cases).

So, I propose that "Data Types and Literal Values" become section 3, then Parameters will be section 4. 
This would be a rather large diff because of moving a large section so I won't otherwise change any text

**Comment by msdemlei** [comment]
On Wed, Jul 05, 2023 at 09:05:32AM -0700, Patrick Dowler wrote:
> So, I propose that "Data Types and Literal Values" become section
> 3, then Parameters will be section 4.

That *is* a bit of a pain because references to "DALI, sect. 3" will
break in that way if people blindly update the version-sharp
references, which ivoatex entices them to do ("make
bib-suggestions").

But it's really the right thing to do, so you have my blessing.

> This would be a rather large diff so diff

Um... that I don't get.  Wouldn't this just be subsection -> section,
and hence a tiny diff?

**Comment by molinaro-m** [comment]
>> This would be a rather large diff so diff

> Um... that I don't get. Wouldn't this just be subsection -> section, and hence a tiny diff?

I think it means Sec. 3.3 moving to Sec. 3, so text will have to flow around besides the section numbering.

**Comment by pdowler** [comment]
yes, this subsection is in between others in 3, so it would need to move upward to become 3 and them Parameters would become 4. 

the alternative is that I move it down so irt becomes 4, only the current 3.4 gets renamed to 3.3... either way, "Responses" goes from 4 to 5. Plus I don't think that's the best order in the doc.

I'll do it and see how it looks :-)
